[versions]
compileSdk = "33"
targetSdk = "33"
minSdk = "24"

accompanist = "0.25.1"
activityCompose = "1.5.1"
appcompat = "1.5.1"
amplify = "1.37.3"
androidxEspresso = "3.4.0"
androidxJunit = "1.1.3"
buildTools = "7.3.0"
compose = "1.2.1"
composeCompiler = "1.3.1"
core = "1.9.0"
crashlytics = "2.9.2"
datastore = "1.0.0"
desugarJdkLibs = "1.1.5"
detekt = "1.21.0"
detektCompose = "1.2.1"
dialogCore = "0.8.1-rc"
firebaseBom = "30.5.0"
googleServices = "4.3.14"
javapoet = "1.13.0"
junit = "4.13.2"
hilt = "2.43.2"
kotlin = "1.7.10"
leakcanaryAndroid = "2.9.1"
lifecycle = "2.5.1"
navigationCompose = "2.5.2"
navigationComposeHilt = "1.0.0"
playServicesLocation = "20.0.0"
mapbox = "10.8.0"
versions = "0.42.0"

[libraries]
gradle-plugin-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "crashlytics" }
gradle-plugin-buildtools = { module = "com.android.tools.build:gradle", version.ref = "buildTools" }
gradle-plugin-detekt-compose = { module = "ru.kode:detekt-rules-compose", version.ref = "detektCompose" }
gradle-plugin-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
gradle-plugin-googleservices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle-plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions" }

accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }

mapbox-android = { module = "com.mapbox.maps:android", version.ref = "mapbox" }

amplify-core = { module = "com.amplifyframework:core", version.ref = "amplify" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore"}
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-compose-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "navigationComposeHilt" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

compose-material-dialog-core = { module = "io.github.vanpra.compose-material-dialogs:core", version.ref = "dialogCore" }
compose-material-dialog-datetime = { module = "io.github.vanpra.compose-material-dialogs:datetime", version.ref = "dialogCore" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }

javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

junit = { module = "junit:junit", version.ref = "junit" }

leakcanaryAndroid = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
