package com.epmedu.animeal.base.theme

import androidx.compose.ui.graphics.Color

/**
 * names generated by https://chir.ag/projects/name-that-color
 */
val RobinsEggBlue = Color(0xFF03BFD7)
val Daintree = Color(0xFF00283D)

val DisabledButtonColor = Color(0xFFD9DEE1)
val DisabledButtonContentColor = Color.White