package com.epmedu.animeal.base.theme

import androidx.compose.ui.graphics.Color

/**
 * names generated by https://www.color-name.com/
 */
internal object AnimealColor {

    object Light {
        val CarminePink = Color(0xFFF04E45)
        val Gainsboro = Color(0xFFDFDFDF)
        val SeaSerpent = Color(0xFF03BFD7)
        val Daintree = Color(0xFF00283D)
        val DarkGunMetal = Color(0xFF212530)
    }
}

object CustomColor {
    val Facebook = Color(0xFF438BED)
    val Google = Color(0xFF000000)
}
