package com.epmedu.animeal.base.theme

import androidx.compose.ui.graphics.Color

/**
 * names generated by https://www.color-name.com/
 */
val SeaSerpent = Color(0xFF03BFD7)
val Daintree = Color(0xFF00283D)
val Gainsboro = Color(0xFFD9DEE1)
val DarkGunMetal = Color(0xFF212530)