name: Debug CI workflow

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    
    env:
      AWS_CONFIGURATION_BASE64: ${{ secrets.AWS_CONFIGURATION }}
      AMPLIFY_CONFIGURATION_BASE64: ${{ secrets.AMPLIFY_CONFIGURATION }}
      GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Create aws configuration file
        run: |
          echo $AWS_CONFIGURATION_BASE64 | base64 --decode > awsconfiguration.json
        
      - name: Create amplify configuration file
        run: |
          echo $AMPLIFY_CONFIGURATION_BASE64 | base64 --decode > amplifyconfiguration.json
          
      - name: Restore gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
          echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Run Detekt
        run: ./gradlew detekt

  unit_tests:
    needs: [detekt]
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Run Unit Tests
        run: ./gradlew test

#  android_tests:
#    needs: [unit_tests]
#    name: Instrumentation Tests
#   runs-on: macos-latest
#   steps:
#     - uses: actions/checkout@v2
      
#      - name: Setup Java 11
#        uses: actions/setup-java@v1
#        with: {java-version: 11}
      
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2

#      - name: Run Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
          
  build_apk:
    needs: [unit_tests]
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
        
