name: Debug CI workflow

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Executing secret-directory preparing script
        env:
          AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
          AWS_CONFIGURATION: ${{ secrets.AWS_CONFIGURATION }}
        run: |
          # keep track of the present-working-directoring on startup so we can return to it
          initial_dir=`pwd`

          # ensure we have the directory we will be using for our secrets
          mkdir -p ~/secrets

          cd ~/secrets
          secrets_dir=`pwd`

          # populate the content of the secrets-dir to be as expected
          echo $AMPLIFY_CONFIGURATION >> amplifyconfiguration.json
          echo $AWS_CONFIGURATION >> awsconfiguration.json


          # ensure we have the directory where we will be writing our gradle-properties file
          mkdir -p ~/.gradle

          # set the gradle-properties constant
          cd ~/.gradle
          echo "ANIMEAL_SECRETS_FOLDER=~/secrets" >> gradle.properties

          # return to the starting present-working-directoring
          cd $initial_dir

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Run Detekt
        run: ./gradlew detekt

  unit_tests:
    needs: [detekt]
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Run Unit Tests
        run: ./gradlew test

#  android_tests:
#    needs: [unit_tests]
#    name: Instrumentation Tests
#   runs-on: macos-latest
#   steps:
#     - uses: actions/checkout@v3
      
#      - name: Setup Java 11
#        uses: actions/setup-java@v1
#        with: {java-version: 11}
      
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2

#      - name: Run Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
          
  build_apk:
    needs: [unit_tests]
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
        
