
name: Debug CI workflow

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Run Unit Tests
        run: ./gradlew test

  android_tests:
    name: Instrumentation Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest
