name: Debug CI workflow

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Configure Amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: init
          amplify_env: test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Run Detekt
        run: ./gradlew detekt

  unit_tests:
    needs: [detekt]
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Run Unit Tests
        run: ./gradlew test

#  android_tests:
#    needs: [unit_tests]
#    name: Instrumentation Tests
#   runs-on: macos-latest
#   steps:
#     - uses: actions/checkout@v2
      
#      - name: Setup Java 11
#        uses: actions/setup-java@v1
#        with: {java-version: 11}
      
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2

#      - name: Run Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
          
  build_apk:
    needs: [unit_tests]
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
        
