name: Debug CI workflow

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  prep_secrets:
    name: Prepare environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Retrieve the secret and decode it to a file
        env:
          AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
          AWS_CONFIGURATION: ${{ secrets.AWS_CONFIGURATION }}
        run: |
          echo "printing value of env-var - AWS_CONFIGURATION -- ${AWS_CONFIGURATION}"

      - name: Executing secret-directory preparing script
        run: |
          # keep track of the present-working-directoring on startup so we can return to it
          initial_dir=`pwd`
          #echo "started-at-dir: $initial_dir"

          # ensure we have the directory we will be using for our secrets
          mkdir -p ~/secrets

          cd ~/secrets
          secrets_dir=`pwd`

          # populate the content of the secrets-dir to be as expected
          echo $AMPLIFY_CONFIGURATION | base64 --decode > amplifyconfiguration.json
          echo $AWS_CONFIGURATION | base64 --decode > awsconfiguration.json


          # ensure we have the directory where we will be writing our gradle-properties file
          mkdir -p ~/.gradle

          # set the gradle-properties constant
          cd ~/.gradle
          echo "\nANIMEAL_SECRETS_FOLDER=${secrets_dir}" >> gradle.properties


          # return to the starting present-working-directoring
          cd $initial_dir

  detekt:
    needs: [prep_secrets]
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Run Detekt
        run: ./gradlew detekt

  unit_tests:
    needs: [detekt]
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Run Unit Tests
        run: ./gradlew test

#  android_tests:
#    needs: [unit_tests]
#    name: Instrumentation Tests
#   runs-on: macos-latest
#   steps:
#     - uses: actions/checkout@v3
      
#      - name: Setup Java 11
#        uses: actions/setup-java@v1
#        with: {java-version: 11}
      
#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2

#      - name: Run Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
          
  build_apk:
    needs: [unit_tests]
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
        
