name: CI

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  Unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: Run unit tests
        run: ./gradlew test
