name: Release workflow

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

env:
  AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
  AWS_CONFIGURATION: ${{ secrets.AWS_CONFIGURATION }}
  GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
  KEY_STORE_FILE: ${{ secrets.KEY_STORE }}

jobs:
  build:
    name: Build Animeal Application
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - uses: actions/checkout@v3

      - name: Copy google services config
        run: echo $GOOGLE_SERVICES >> app/google-services.json

      - name: Copy amplify config files
        run: |
          mkdir -p app/src/main/res/raw
          echo $AMPLIFY_CONFIGURATION >> app/src/main/res/raw/amplifyconfiguration.json
          echo $AWS_CONFIGURATION >> app/src/main/res/raw/awsconfiguration.json

      - name: Copy key
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/app/animeal_key_store.jks
          encodedString: $KEY_STORE_FILE
      
      - name: Console
        run: echo ${{ github.workspace }}/app/keystore.jks

      - name: "Check keystore existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "app/animeal_key_store.jks"
       
      - name: sign report
        run: ./gradlew signingReport

      - name: Build APK
        run: ./gradlew clean assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/release/app-release.apk
