name: Release workflow

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

env:
  AMPLIFY_CONFIGURATION: ${{ secrets.AMPLIFY_CONFIGURATION }}
  AWS_CONFIGURATION: ${{ secrets.AWS_CONFIGURATION }}
  GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
  KEY_STORE_FILE: ${{ secrets.KEY_STORE }}
  FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT }}

jobs:
  build:
    name: Build Animeal Application
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - uses: actions/checkout@v3

      - name: Copy google services config
        run: echo $GOOGLE_SERVICES >> app/google-services.json

      - name: Copy amplify config files
        run: |
          mkdir -p app/src/main/res/raw
          echo $AMPLIFY_CONFIGURATION >> app/src/main/res/raw/amplifyconfiguration.json
          echo $AWS_CONFIGURATION >> app/src/main/res/raw/awsconfiguration.json

      - name: Copy key
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/app/animeal_key_store.jks
          encodedString: ${{ secrets.KEY_STORE }}

      - name: "Check keystore existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "app/animeal_key_store.jks"

      - name: Build release APK
        run: ./gradlew clean assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/release/app-release.apk
     
      - name: Create Google Service Account.json
        run: echo $FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON >> service_account.json
          
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFile: service_account.json
          groups: qa_team
          file: app/build/outputs/apk/release/app-release.apk
